kind: Config
apiVersion: v1
current-context: nks-user@kubernetes
clusters:
- name: kubernetes
  cluster:
    server: https://8b3ddd7e-d557-41f3-84f4-696456083437.kr.vnks.ntruss.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2VENDQWRHZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQ0FYRFRJeU1URXpNREF3TURreE1sb1lEekl4TWpJeE1UQTJNREF3T1RFeVdqQVZNUk13RVFZRApWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBCndMYTZOTVdkK3VQREFKcEtRL3o0Y3RsdUpqUW83RmY0SkNNNXFNU2NqMnhxZm9HQ2MvdzFreHpRdVBBM3paaXgKQTJjVzU5QzdPWHRWV2tFb2NQNG9IT2tRZW9JWDJKQ3k1NldEVGthYXo5RTVwWm5IYmsyLzNramd3STkzRXRXeApocGluWjVmNmNWeXM5cFgzSnRwRXFIeU5CRURBUUk4NHRJUFNWWkJsL1FtcjJadk5wdXRuTytnekYya2J6Rm1ZCnBkK3pvbVA4MU9FNDlNSkU4VjNGTE1iU0NzWnVCRHZTWVVoRldTeEFwWE9maGtBUHZnRkVjZk1TWFdET3JEd2wKd1B6SFVva3MyM3h0bE4rVm1rWmJPbXRlcWluZDlST2R2blJoWW1xMld2ajE3d05GempGVVJiQjZwbXNudVFFTwpYbkl6M2tSekZuU1RCSmJHTVVwcTdRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WURWUjBUCkFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVUwSVJNVXhCQ3lDdWNWWmtaTS9SejZ2c2I4WWt3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFBRzNQbUZXNnRLZGVoMWNBekxLM2VIN2JFb2pTY0ZEOHBwY2ZsZFRDdkNPR1VregpMYk9qQ2h6bXMycktqUmxYbnpRaVBlVlJqU1hGV3NnYllBUk1sWDNJZ015YVhWcWFvRW81NjFFWnFhSXJydFpvClE1ZmNpMHFhVEVUQldiNlJLd0kwYTBkQm95cXpjTGY5V0lDTEFZY1R3MjVKcFNRbHlXS0dpcFYxZDVQaUR1cnAKc3lua053MjZsSCtrdFNENHdQQ09rcHFuT2RYWlZpSmVKR1JndDF1TEtLeVJFTnJEVmsrVGlrUkV4c2xNaE11eQpoQjNsZksrbmswbjd2U25KSTQ1U0xyTGxrR0ZRRmJyMWpsZ2tKanFndzhIMjJ5ZUxrUERqd0U5MHZWc3FJSWZuClZhZkJqVytwb05VZTdJWnllZ1Rhb0dRc2N3MXlHcTZJUEUzVmt2dz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
contexts:
- name: nks-user@kubernetes
  context:
    cluster: kubernetes
    user: nks-user
users:
- name: nks-user
  user:
    exec:
      command: ncp-iam-authenticator
      args:
      - token
      - --clusterUuid
      - 8b3ddd7e-d557-41f3-84f4-696456083437
      - --region
      - KR
      env: []
      apiVersion: client.authentication.k8s.io/v1beta1
